### ISSUE TITLE
Why map local path when running docker?

### ISSUE THREAD

**Issue by pcnudde** [numerai/numerai-cli#30]
the '-v' option here: https://github.com/numerai/numerai-cli/blob/97c88aeeea241993a1ad961df9b903ce5c6b82a2/numerai/cli/util/docker.py#L109

That seems to break the encapsulation of the docker container. Who knows what people store in that place, it now is visible in docker and worse, writing things in docker will show up on my local filesystem. This is not what I expected. (I write submission files in the docker container for example, and did not expect those files to overwrite files I had on my local system).

Am I missing something?

**Comment by ndharasz** [comment]
You're right this volume does break encapsulation. It was originally meant to enable hot-reloading (meaning the docker container would need access to real-time files without re-building), but since this is only used in `numerai node test` commands, which builds the container each time so it's a little useless at this point.

I'll include this change in my 0.3.1 update.

**Comment by ndharasz** [comment]
will be fixed in:
https://github.com/numerai/numerai-cli/pull/36
